accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView,HomeView,
    UserLoginView, UserLogoutView,
    ProfileEditView, UserListView,
)
from . import views


app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'),
    path('userlist/', UserListView.as_view(), name='userlist'),
    path('mk_relation/<int:pk>/', views.mk_relation, name='mk_relation'),
    path('rm_relation/<int:pk>/', views.rm_relation, name='rm_relation'),
]

microposts/urls.py
from django.urls import path
from .views import (
    PostCreateView, PostListView, PostUpdateView, PostDeleteView, MyPostsView
)
from . import views

app_name = 'microposts'
urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('postlist/', PostListView.as_view(), name='postlist'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
    path('myposts/', MyPostsView.as_view(), name='myposts'),
    path('add_favourite/<int:pk>/', views.add_favourite, name='add_favourite'),
    path('rm_favourite/<int:pk>/', views.remove_favourite, name='rm_favourite'),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings  # mediaを使うために追加

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('microposts/', include('microposts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microposts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    # Postのオーナーを設定する
    owner = models.ForeignKey('accounts.User', verbose_name='オーナー', on_delete=models.CASCADE)
    content = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'posts'

microposts/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30,
                        'placeholder': 'ここに入力してください'}
            ),
        }


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30}
            ),
        }

microposts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from .forms import PostCreateForm, PostUpdateForm
from django.contrib import messages
from django.urls import reverse_lazy, reverse


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'microposts/create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('microposts:create')

    def form_valid(self, form):
        # formに問題なければ、owner id に自分のUser idを割り当てる
        # request.userが一つのセットでAuthenticationMiddlewareでセットされている。
        form.instance.owner_id = self.request.user.id
        messages.success(self.request, '投稿が完了しました')
        return super(PostCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '投稿が失敗しました')
        return redirect('microposts:create')


class PostListView(LoginRequiredMixin, ListView):
    # テンプレートを指定
    template_name = 'microposts/postlist.html'
    # 利用するモデルを指定
    model = Post
    # ページネーションの表示件数
    paginate_by = 3

    # Postsテーブルの全データを取得するメソッド定義
    # テンプレートでは、object_listとしてreturnの値が渡される
    def get_queryset(self):
        return Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['favourite_list'] = user.favourite_post.all()

        return context


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'microposts/update.html'
    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super(PostUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('microposts:update', kwargs={'pk': self.object.id})

    def form_invalid(self, form):
        messages.warning(self.request, '更新が失敗しました')
        return reverse('microposts:update', kwargs={'pk': self.object.id})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'microposts/delete.html'

    success_url = reverse_lazy('microposts:create')
    success_message = "投稿は削除されました。"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


class MyPostsView(LoginRequiredMixin, ListView):

    template_name = 'microposts/myposts.html'

    model = Post

    paginate_by = 3

    # Postsテーブルのowner_idが自分自身の全データを取得するメソッド定義
    def get_queryset(self): # 自分の投稿オブジェクトを返す。
        return Post.objects.filter(owner_id=self.request.user)

    def get_context_data(self, **kwargs):
        # デフォルトのコンテキストデータを取得
        context = super().get_context_data(**kwargs)

        # Postsテーブルの自分の投稿数をmy_posts_countへ格納
        context['my_posts_count'] = Post.objects.filter(owner_id=self.request.user).count()
        return context


def add_favourite(request, pk):
    # postのpkをhtmlから取得
    post = get_object_or_404(Post, pk=pk)
    # ログインユーザーを取得
    user = request.user
    # ログインユーザーをfavoritePostのUser_idとして、post_idは
    # 上で取得したPostを記録
    user.favourite_post.add(post)
    return redirect('microposts:postlist')

def remove_favourite(request, pk):
    # postのpkをhtmlから取得
    post = get_object_or_404(Post, pk=pk)
    # ログインユーザーを取得
    user = request.user
    # ログインユーザーをfavoritePostのUser_idとして、post_idは
    # 上で取得したPostを記録
    user.favourite_post.remove(post)
    return redirect('microposts:postlist')

templates/microposts/create.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    {#  views.pyからmessagesが渡された場合にのみメッセージを表示させる。#}
                    {% if messages %}
                        {% for message in messages %}
                            {#   message/tagsはSettings.pyで設定している#}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <h4><b>新規投稿</b></h4>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-outline-primary btn-block">
                                    投稿する
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/microposts/delete.html
{% extends 'base.html' %}
{% block content %}
{#    投稿したユーザーしか削除できない制約を追加#}
    {% if object.owner_id == user.id %}
        <form method="POST">
        {% csrf_token %}
        <p>「{{ object.content }}」を削除しますか？</p>
        <button type="submit" class="btn btn-default btn-danger">
            削除する
        </button>
    </form>
        {% else %}
        <h1>{{ user.get_username }}さんの投稿ではありません。</h1>
    {% endif %}
{% endblock %}

templates/microposts/myposts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <!--ページタイトル-->
                <aside class="col-sm-4">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title text-center">{{ user.get_username }}</h3>
                        </div>
                        <div class="card-body">
                            {# ユーザーがプロフィール画像を持っている場合#}
                            {% if user.avatar %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                                {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                            {% else %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                            {% endif %}
                        </div>
                        <a class="btn btn-outline-secondary btn-sm"
                            href="{% url 'accounts:edit_profile' %}" role="button">プロフィール更新</a>
                    </div>
                </aside>
                <div class="col-sm-8">
                    <ul class="nav nav-tabs nav-justified mb-3">
                        <li class="nav-item"><a href="{% url 'microposts:myposts' %}" class="nav-link active">MyPosts一覧
                            {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                            <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Followings
                            {#  フォロワー数を表示#}
                            <span class="badge badge-secondary">"#"</span></a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Followers
                            {#  フォロワー数を表示#}
                            <span class="badge badge-secondary">"#"</span></a></li>
                    </ul>
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='post_list'
                                class="table table-striped table-bordered table-hover">
                            　<!-- 表の列の定義-->
                            <thead>
                            <tr>
                                <th class="text-center" style="width: 80%">投稿内容</th>
                                <th class="text-center" style="width: 20%">更新／削除</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {% for item in object_list %}
                                <tr class="text">
                                    <td class="text"><h6>@{{ item.created_at }}</h6>{{ item.content }}</td>
                                    <td class="text-center align-middle">
                                        {#  pkを指定する際は、urlタグはやや特殊な書き方となる↓以下参照#}
                                        <a class="btn btn-outline-success btn-sm"
                                            href="{% url 'microposts:update' item.pk %}"
                                            role="button">更新</a>
                                        <a class="btn btn-outline-danger btn-sm"
                                            href="{% url 'microposts:delete' item.pk %}"
                                            role="button">削除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                    {#   django-bootstrap4のページネーション#}
                    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/microposts/postlist.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <!--ページタイトル-->
            <div class="card mb-3">
                <div class="card-header">
                    <h4><b>投稿一覧</b></h4>
                </div>
                <div class="card-body">
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='post_list' class="table table-striped table-bordered table-hover">
                            <!-- 表の列の定義-->
                            <thead>
                            <tr>
                                <th class="text-center">投稿内容</th>
                                <th class="text-center">お気に入り</th>
                            </tr>
                            </thead>
                            <!-- ここまでが表の列の定義-->
                            <!-- 表のデータ部分の表示-->
                            <tbody>
                            {# デフォルトはobject_listとなるが、view.pyでcontextとして指定#}
                            {% for item in object_list %}
                                <tr class="text">
                                    <td class="text" style="width: 80%">
                                        <h6>{{ item.owner }}@{{ item.created_at}}</h6>{{ item.content }}</td>
                                    <td class="text-center align-middle" style="width: 20%">
                                        {#  pkを指定する際は、urlタグはやや特殊な書き方となる↓以下参照#}
                                        {#  favorite_list に itemがあれば（すでにお気に入り登録されていれば）#}
                                        {% if item in favourite_list %}
                                            <form action="{% url 'microposts:rm_favourite' pk=item.pk %}" method="post">
                                                <button type="submit" class="btn btn-link" name="button">
                                                    <i class="fas fa-thumbs-up"></i>
                                                </button>
                                                {% csrf_token %}
                                            </form>
                                        {% else %}
                                            {#  object_listの要素をitemとして取り出しているので、item.pkでpk取得#}
                                            <form action="{% url 'microposts:add_favourite' pk=item.pk %}" method="post">
                                                <button type="submit" class="btn btn-link" name="button">
                                                    <i class="far fa-thumbs-up"></i>
                                                </button>
                                                {% csrf_token %}
                                            </form>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                    {#   django-bootstrap4のページネーション#}
                    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/microposts/update.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    {#  views.pyからmessagesが渡された場合にのみメッセージを表示させる。#}
                    {% if messages %}
                        {% for message in messages %}
                            {#   message/tagsはSettings.pyで設定している#}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <h4><b>投稿の更新</b></h4>
                        </div>
                        {#  投稿したユーザーしか削除できない制約を追加#}
                        {% if object.owner_id == user.id %}
                            <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-outline-success btn-block">
                                    更新する
                                </button>
                            </form>
                        {% else %}
                            <p class='font-weight-bold text-danger text-center'>
                                {{ user.get_username }}さんの投稿ではありません。
                            </p>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}